### ISSUE TITLE
Suggestion: Unused characters in Lego Pirates of the Caribbean 

### ISSUE THREAD

**Issue by TreeFortress2** [Calvineries/Lego-Games-Character-List#1]
I think that there are probably some really cool unused characters in LPOTC, I'd like to see what you can find!

**Comment by Calvineries** [comment]
> I think that there are probably some really cool unused characters in LPOTC, I'd like to see what you can find!

I added the game!
Here's what I found: https://github.com/Calvineries/Lego-Games-Character-List/blob/main/pirates-of-the-caribbean.md
